### ISSUE TITLE
Possible race in creation / parenting of windows

### ISSUE THREAD

**Issue by kov** [Igalia/chromium#161]
While working with CEF on top of this codebase we are hitting a race where WindowTree::AddWindow is sometimes reached before the root window is known (i.e. WindowTree::AddRoot has been called), so it hits the 'no parent' error case there and then the inflight change crashes it.

Have you seen this behaviour yet? I believe it might not happen in chrome - we have been testing using cefsimple - due to it handling WindowTreeHost creation differently.

I managed to work-around the race by making platform window creation sync, but there is probably a better way. Any thoughts?

https://git.collabora.com/cgit/cef-wayland/chromium.git/commit/?h=wip/kov&id=24e5fc98673e3a982d026069d5e163230c8ab1de

**Comment by tonikitoo** [comment]
I believe to have seen this bug while testing locally:

$ out/ozone/linux_os/chrome --mus --ozone-platform=x11 --user-data-dir=~/tmpp000-------aasdfadsfkaa  --use-gl=egl 
[38919:38924:0731/002132.399825:482942549117:INFO:service_process_launcher.cc(197)] Launched child process pid=38926, instance=, name=ui, user_id=2d4d86a8-372c-4cca-847a-4295ae33f0b3
[38919:38924:0731/002132.400925:482942550213:INFO:service_process_launcher.cc(197)] Launched child process pid=38927, instance=, name=content_packaged_services, user_id=a65bc6b2-96b1-4be7-8fc4-452af8735f41
[38927:38927:0731/002133.816256:ERROR:in_flight_change.cc(103)] change failed, type=0
[38927:38927:0731/002133.816290:FATAL:in_flight_change.cc(104)] Check failed: false. 
#0 0x55bb84fea4a7 base::debug::StackTrace::StackTrace()
#1 0x55bb85003b31 logging::LogMessage::~LogMessage()
#2 0x55bb8625b29b aura::CrashInFlightChange::ChangeFailed()
#3 0x55bb86246772 aura::WindowTreeClient::OnChangeCompleted()
#4 0x55bb83734430 ui::mojom::WindowTreeClientStubDispatch::Accept()
#5 0x55bb85b34dfc mojo::InterfaceEndpointClient::HandleValidatedMessage()
#6 0x55bb85b34a56 mojo::FilterChain::Accept()
#7 0x55bb85b361fc mojo::InterfaceEndpointClient::HandleIncomingMessage()
#8 0x55bb85b3da71 mojo::internal::MultiplexRouter::ProcessIncomingMessage()
#9 0x55bb85b3d2a5 mojo::internal::MultiplexRouter::Accept()
#10 0x55bb85b34a56 mojo::FilterChain::Accept()
#11 0x55bb85b33c01 mojo::Connector::ReadSingleMessage()
#12 0x55bb85b34632 mojo::Connector::ReadAllAvailableMessages()
#13 0x55bb85b344ac mojo::Connector::OnHandleReadyInternal()
#14 0x55bb839b2030 content::(anonymous namespace)::DeferredCallback()
#15 0x55bb85b4a80d mojo::SimpleWatcher::OnHandleReady()
#16 0x55bb8347f0ac _ZN4base8internal12InvokeHelperILb1EvE8MakeItSoIRKMN5media22DecryptingAudioDecoderEFviNS4_9Decryptor6StatusERKNSt3__14listI13scoped_refptrINS4_11AudioBufferEENS8_9allocatorISC_EEEEERKNS_7WeakPtrIS5_EEJRKiS7_SH_EEEvOT_OT0_DpOT1_
#17 0x55bb8509905b base::debug::TaskAnnotator::RunTask()
#18 0x55bb8500abba base::MessageLoop::RunTask()
#19 0x55bb8500aef2 base::MessageLoop::DeferOrRunPendingTask()
#20 0x55bb8500b1d4 base::MessageLoop::DoWork()
#21 0x55bb8500d889 base::MessagePumpLibevent::Run()
#22 0x55bb8500a77f base::MessageLoop::Run()
#23 0x55bb85033ae7 base::RunLoop::Run()
#24 0x55bb84ec003c ChromeBrowserMainParts::MainMessageLoopRun()
#25 0x55bb83a1c032 content::BrowserMainLoop::RunMainMessageLoopParts()
#26 0x55bb83a1ed0b content::BrowserMainRunnerImpl::Run()
#27 0x55bb83a17618 content::BrowserMain()
#28 0x55bb84c53c5c content::RunNamedProcessTypeMain()
#29 0x55bb84c545c8 content::ContentMainRunnerImpl::Run()
#30 0x55bb84c710b6 service_manager::Main()
#31 0x55bb84c53072 content::ContentMain()
#32 0x55bb8330a38d ChromeMain

is that how it looks like, kov?

**Comment by kov** [comment]
Yep! That's the one.

**Comment by tonikitoo** [comment]
I think I know what is going one with this bug:

I have a more recurring situation with Chromium/Mus: it is indeed a problem that we saw with the refactor branch and services_unittests, PR #141: messages reaching the WS out of order, because they were sent through different mojo pipes.

log of when it succeeds:

WindowTree::NewWindow:1516 client_id:65545
	WindowTree::NewWindow:505 client_id:65545
WindowTreeHostFactory::CreatePlatformWindow:33 transport_window_id:65546
WindowTreeHostFactory::CreatePlatformWindow:71 transport_window_id:65546 (before ::AddRoot)
WindowTreeHostFactory::CreatePlatformWindow:73 transport_window_id:65546 (after ::AddRoot)
WindowTree::AddTransientWindow:562 window_id:65537 transient_window:65546 window:0x147344723500 transient_window:0x14734547c500

--> in the first case, ::CreatePlatformWindow is called before, and we have a valid window for when WindowTree::AddTransientWindow is called.

log of when it fails:
WindowTree::NewWindow:1516 client_id:65545
	WindowTree::NewWindow:505 client_id:65545
WindowTree::AddTransientWindow:566 window_id:65537 transient_window:65546 window:0x347863b03500 transient_window:(nil)
WindowTreeHostFactory::CreatePlatformWindow:33 transport_window_id:65546
WindowTreeHostFactory::CreatePlatformWindow:71 transport_window_id:65546 (before ::AddRoot)
WindowTreeHostFactory::CreatePlatformWindow:73 transport_window_id:65546 (after ::AddRoot)


---> here, due to mojo not ensuring ordering when pipes are different, WindowTree::AddTransientWindow is called before WindowTreeHostFactory::CreatedPlatformWindow is called, and boom...

**Comment by tonikitoo** [comment]
Solution up for review: https://github.com/Igalia/chromium/pull/174.

**Comment by tonikitoo** [comment]
Should be fixed by PR #174 .
