### ISSUE TITLE
[ozone/wayland] pressing ALT alternate focus between content and 3-dot menu button

### ISSUE THREAD

**Issue by tonikitoo** [Igalia/chromium#331]
This by pressing ALT focus alternates between content and 3-dot.

This does not happen on ozone/x11 or chrome/x11.

**Comment by tonikitoo** [comment]
investigating this a bit.

**Comment by msisov** [comment]
the #333 brings more problems rather than a good solution.

1) Auto repeat is buggy: that is, if you alternate with alt+tab between the chromium window and something else, and return back to chromium window again, you are no longer able to enter anything with a keyboard. The problem is that modifiers are stored in such a way that ALT is always kept pressed. Previously, we updated modifiers on WaylandKeyboard::Modifiers on call. And modifiers were provided by Wayland. But now, we just rely on pressed alt or whatever keys.

2) Another problem is again when you alternate with alt+tab. What KeyboardEvded does is that it gets stuck with key repeating and just sends the same key all over again and again. Going to provide a solution to this problem.

**Comment by tonikitoo** [comment]
Hopefully fixed by PR #333 and PR #334 (Thanks for the fixup!).

**Comment by tonikitoo** [comment]
Commit upstream (https://chromium-review.googlesource.com/c/chromium/src/+/822871), but reverted after discussing with spang@ (https://chromium-review.googlesource.com/c/chromium/src/+/832886).

Reopening.

**Comment by tonikitoo** [comment]
PR #344 is an alternative solution. spang@ was contacted on IRC to make sure ui::KeyboardModifiers can be used from within Ozone/Wayland.

**Comment by tonikitoo** [comment]
Should be fixed by PR #344.
